### PR TITLE
Initial Addition of Download Page

### PR DESCRIPTION
**Pull request by AnthonyDionise**
initial: create download page

### CODE REVIEW

**Comment by AnthonyDionise** [comment]
Create download page with template

**Comment by berryma4** [comment]
Could you add one for the general common product.
So, the top would be Download CS-Studio, then below would be , 'Site Specific Versions' (ie. SNS)

**Comment by AnthonyDionise** [comment]
yup, just did!

**Comment by berryma4** [comment]
I'm sorry ... more like:

Download CS-Studio

Site Specific Versions:

SNS, DESY, NSLSII, etc.

**Comment by AnthonyDionise** [comment]
I made the changes, is this better?

**Comment by berryma4** [comment]
yes.  For now, can yo make the cs-studio download link:
https://openepics.ci.cloudbees.com/view/CS-Studio%204.0/job/CS-Studio%20-%20Release%20-%204.0/

**Comment by AnthonyDionise** [comment]
yup, no problem

**Comment by AnthonyDionise** [comment]
Final changes made

**Pull request merged**
